version: 2.1

jobs:
  node-js-job:
    docker:
      - image: timbru31/java-node:latest
    steps:
      - checkout
      - run:
          name: Update Node.js to v22
          command: |
            npm install -g n
            n 22.11.0
            node -v
      - run:
          name: Get access
          command: chmod 777 /root
      - run:
          name: Update dependencies
          command: apt update && apt upgrade -y
      - run:
          name: Install libs
          command: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
      - run:
          name: Update Cypress
          command: npm install cypress --save-dev
      - run:
          name: Install Allure Commandline
          command: npm install -g allure-commandline --save-dev
      - run:
          name: Install Gatling CLI
          command: npm install -g @gatling.io/cli
      - run:
          name: Give execution permissions to Allure
          command: chmod +x $(which allure)
      - run:
          name: Install project dependencies
          command: npm i
          
      # Run Cypress tests
      - run:
          name: Run Cypress tests
          command: npm run cy || true
          
      # Generate Allure report for Cypress tests
      - run:
          name: Generate Allure Report for Cypress
          command: npm run allure:report
          
      # Run Gatling performance tests
      - run:
          name: Run Gatling Performance Tests
          command: npm run gatling
          
      # Move Gatling reports to a specific folder for artifact storage
      - run:
          name: Move Gatling Reports
          command: cd gatling && npm run move-reports
          
      # Store Allure report as an artifact
      - store_artifacts:
          path: allure-report
          destination: CypressReport
          
      # Store Gatling performance report as an artifact
      - store_artifacts:
          path: gatling-report
          destination: GatlingReport

workflows:
  build-and-test:
    jobs:
      - node-js-job
