version: 2.1

jobs:
  node-js-job:
    docker:
      - image: cimg/node:22.11.0-browsers
    steps:
      - checkout
      - run:
          name: Install Allure Commandline
          command: npm install -g allure-commandline --save-dev
      - run:
          name: Install Gatling CLI
          command: npm install -g @gatling.io/cli
      - run:
          name: Install project dependencies
          command: npm i
          
      # Run Cypress tests
      - run:
          name: Run Cypress tests
          command: npm run cy || true
          
      # Generate Allure report for Cypress tests
      - run:
          name: Generate Allure Report for Cypress
          command: npm run allure:report
          
      # Run Gatling performance tests
      - run:
          name: Run Gatling Performance Tests
          command: npm run gatling
          
      # Move Gatling reports to a specific folder for artifact storage
      - run:
          name: Move Gatling Reports
          command: cd gatling && npm run move-reports
          
      # Store Allure report as an artifact
      - store_artifacts:
          path: allure-report
          destination: CypressReport
          
      # Store Gatling performance report as an artifact
      - store_artifacts:
          path: gatling-report
          destination: GatlingReport

workflows:
  build-and-test:
    jobs:
      - node-js-job
